# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

def common_pods
  use_frameworks!
  pod 'MJRefresh'
end

workspace 'PJ/PJ.xcworkspace'
target 'PJ' do
  common_pods
  
  target 'PJTests' do
    inherit! :search_paths
  end
  
  target 'PJUITests' do
    
  end
  
end

target 'Static' do
  project 'Static/Static.xcodeproj'
  common_pods
end

target 'PJSub' do
  project 'PJSub/PJSub.xcodeproj'
  common_pods
end
